export const GET_USER_GRAPH_REQUEST = 'GET_USER_GRAPH_REQUEST'
export const GET_USER_GRAPH_SUCCESS = 'GET_USER_GRAPH_SUCCESS'
export const GET_STATS_GRAPH_REQUEST = 'GET_STATS_GRAPH_REQUEST'
export const GET_STATS_GRAPH_SUCCESS = 'GET_STATS_GRAPH_SUCCESS'